### ISSUE TITLE
InternalOpenIDError: Failed to discover OP endpoint URL

### ISSUE THREAD

**Issue by jackzuan** [kevalane/sign-in-through-steam#2]
Test your code,it can not running .  
push online test url:　https://6yang.top
InternalOpenIDError: Failed to discover OP endpoint URL
    at /web/dev/web/nodejs/signsteam/node_modules/@passport-next/passport-openid/lib/passport-openid/strategy.js:249:52
    at /web/dev/web/nodejs/signsteam/node_modules/openid/openid.js:757:14
    at /web/dev/web/nodejs/signsteam/node_modules/openid/openid.js:547:13
    at /web/dev/web/nodejs/signsteam/node_modules/openid/openid.js:503:11
    at /web/dev/web/nodejs/signsteam/node_modules/openid/http.js:41:9
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

help !
thanks

**Comment by jackzuan** [comment]
![image](https://github.com/kevalane/sign-in-through-steam/assets/1006029/d5661e69-1b0c-4fed-9755-98d1b96f5f4e)
